### ISSUE TITLE
Detalle quest "Investiga las catatumbas Amani" 

### ISSUE THREAD

**Issue by NioGM** [FirelandsProject/bugtracker#1]
### ¿Con qué cliente juegas?

esES

### Faction

Horda

### Comportamiento actual

La misión consiste en quemar ciertos cuerpos en unas tumbas. La quest funciona, y lo único que le falla es un pequeño detalle. Cuando usas el item (una antorcha) y quemas los cuerpos estos cuerpos no desaparece. Además, pasados unos 6 segundos, puedes volver a quemar el cuerpo y te volverá a contar para la quest. 

![WoWScrnShot_090422_132413](https://user-images.githubusercontent.com/112731215/188329868-5e17a1f1-21d9-46d2-934f-c9064458091d.jpg)

![WoWScrnShot_090422_132419](https://user-images.githubusercontent.com/112731215/188329871-a4b7f93a-8572-4012-8313-bcc55c0c47f3.jpg)

![WoWScrnShot_090422_132426](https://user-images.githubusercontent.com/112731215/188329873-186343ed-2c2a-4e2e-a629-a21b885412cd.jpg)

![WoWScrnShot_090422_132434](https://user-images.githubusercontent.com/112731215/188329875-e6cb7182-e373-4864-a181-2265ccb93806.jpg)

![WoWScrnShot_090422_132441](https://user-images.githubusercontent.com/112731215/188329876-2ac73e67-1173-40f6-8a6f-ca7313d170e7.jpg)

![WoWScrnShot_090422_132444](https://user-images.githubusercontent.com/112731215/188329877-e63f23ef-2791-4f90-b757-6ecdbe135462.jpg)

### Comportamiento esperado Blizzlike

Debería tener una pequeña animación que queme el cuerpo y lo desaparezca, después de unos minutos respawnear el cuerpo para volver a ser quemado. 

### Enlaces

- https://es.wowhead.com/quest=9193/investiga-las-catacumbas-amani
- https://www.youtube.com/watch?v=J7LF99tzedk (Se aprecia en el minuto 1:45) 

### Pasos para reproducir el problema

1. Agarra la quest
2. Usa el item para quemar el cuerpo. 

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/6c8b4fd4203d099c0020cf24f6c30c9ff75e6c59

### Sistema operativo

Debian 11

### Servidor

Firelands

**Comment by SargeroDeV** [comment]
You can close, this is already corrected.

**Comment by pangolp** [comment]
> You can close, this is already corrected.

Podes hablar en español aca. La idea, es que si el reporte fue hecho en español, tengamos la conversación en ese idioma. ¿En que PR fue corregido esto?
