### ISSUE TITLE
Dummys moviéndose 

### ISSUE THREAD

**Issue by NioGM** [FirelandsProject/bugtracker#2]
### ¿Con qué cliente juegas?

esES

### Faction

Ambos

### Comportamiento actual

Cuando le pegas a los Dummies de las algunos zonas iniciales se mueven.

El error se presenta, en la zona inicial de: 

- Elfos de la noche.
- No muertos. 
- Trolls. 

En los Golbin hay algo curioso, solo un dummy se mueve y aunque lo ataques no te ataca, realmente no se si está bug, o alguna cosas rara de tecnología golbin. 

### Comportamiento esperado Blizzlike

Simplemente no deberían moverse. 

### Enlaces

![WoWScrnShot_090422_150118](https://user-images.githubusercontent.com/112731215/188333296-4e02b480-a7f9-466c-9372-95eb6b368b74.jpg)

![WoWScrnShot_090422_150955](https://user-images.githubusercontent.com/112731215/188333308-f22856a3-d096-4915-b92e-4dd8b1949888.jpg)

![WoWScrnShot_090422_151528](https://user-images.githubusercontent.com/112731215/188333314-fe453b93-2428-4450-9d88-e678eac58ef4.jpg)

![WoWScrnShot_090422_151516](https://user-images.githubusercontent.com/112731215/188333317-44db9b1c-43e7-4755-a637-f699632ea22c.jpg)

### Pasos para reproducir el problema

1. Simplmente atacar los dummies.

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/6c8b4fd4203d099c0020cf24f6c30c9ff75e6c59

### Sistema operativo

Debian 11

### Servidor

Firelands

**Comment by pangolp** [comment]
Gracias. En un rato lo revisó y lo fixeo porqué había visto que pasaba con algunas clases, pero no los había testeado con todos. Por lo que entonces, no es el mismo dummy, debe ser uno diferente, si no, faltarían todos.
