### ISSUE TITLE
Dos detalles en la zona inicial de los no muertos. 

### ISSUE THREAD

**Issue by NioGM** [FirelandsProject/bugtracker#3]
### ¿Con qué cliente juegas?

esES

### Faction

Horda

### Comportamiento actual

1. Hay unos cuantos ángeles en la zona inicial de los no muertos lo que pasa con ellos es que traspasan el suelo. 

2. Los diálogos, algunos diálogos de la primera zona no toman la variable $n, la que, creo que corresponde al nombre de el personaje del usuario. Dejando el dialogo un poco fuera de foco. 

 

### Comportamiento esperado Blizzlike

1. Simplemente los ángeles deberían volar sobre el piso, no traspasándolo. 

2. Calculo yo, que la variable debería agarrar el nombre del personaje y cohesionarlo con el díalogo. (por lo que pude observar solo lo vi proveniente del NPC llamado Darnell 

### Enlaces

![WoWScrnShot_090422_150752](https://user-images.githubusercontent.com/112731215/188333929-74086e47-41f8-4f33-a4b6-a76971a5f8fa.jpg)
![WoWScrnShot_090422_150802](https://user-images.githubusercontent.com/112731215/188333934-5ae6eb20-89f6-49c0-807e-00eadcfe82d6.jpg)
![WoWScrnShot_090422_150818](https://user-images.githubusercontent.com/112731215/188333942-5e488e97-fc06-444c-bf42-4a1037fab916.jpg)

https://es.wowhead.com/npc=49425/darnell

### Pasos para reproducir el problema

1. Crear un No-muerto. 
2. Las dos cosas se verán tomando las primeras misiones de la zona. 
3. 
4.

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/6c8b4fd4203d099c0020cf24f6c30c9ff75e6c59

### Sistema operativo

Debian 11

### Servidor

Firelands

**Comment by pangolp** [comment]
Si, el $n, hace referencia al nombre del jugador, pero si el emulador no le pasa el jugador, el diálogo no sabe a quién esta dirigido.

Lo de los angeles, dependera de los waypoints o bien, de si le falta algo que les permite volar y por eso están en tierra. También lo voy a revisar. Gracias.

**Comment by SargeroDeV** [comment]
You can close, this is already corrected.

**Comment by pangolp** [comment]
> You can close, this is already corrected.

Yes, it was fixed. Thank you.
