### ISSUE TITLE
[QUEST - GOBLINS] El alma de la fiesta.

### ISSUE THREAD

**Issue by ghost** [FirelandsProject/bugtracker#4]
### ¿Con qué cliente juegas?

esES

### Faction

Horda

### Comportamiento actual

Al aceptar la misión [El alma de la fiesta], te cambia de ropa para entrar a la fiesta como camarero. El problema esta, que al abandonar la misión o completarla con comando, estas como desarmado. No funciona ninguna Spell que requiera de armas.

### Comportamiento esperado Blizzlike

Al aceptar la misión, te acercas a la piscina de al lado y completas la misión entreteniendo a los "Fiesteros". Y al finalizarla o abandonarla, tendrías que poder usar las Spells y las armas.

### Enlaces

- NPC que te ofrece la misión: https://www.wowhead.com/npc=35053/candy-cane
- Misión [El alma de la fiesta]: https://www.wowhead.com/quest=14113/life-of-the-party
- NPC para finalizar la misión: https://www.wowhead.com/npc=34668/sassy-hardwrench

### Pasos para reproducir el problema

1. Iniciar la misión 
2. Abandonar la misión o completarla mediante comando.

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/6c8b4fd4203d099c0020cf24f6c30c9ff75e6c59

### Sistema operativo

Debian 11

### Servidor

Firelands

**Comment by pangolp** [comment]
Excelente @lorder99, ¡buen reporte!

**Comment by seobryn** [comment]
@lorder99  Se realizó un Fix sobre esta mision en https://github.com/FirelandsProject/firelands-cata/pull/81, En cuanto se mezcle podríamos realizar nuevamente una prueba
