### ISSUE TITLE
dummys de entrenamiento fuera de su lugar,zona inicial elfos de la noche

### ISSUE THREAD

**Issue by adri7x** [FirelandsProject/bugtracker#6]
### ¿Con qué cliente juegas?

esMX

### Faction

Alianza

### Comportamiento actual

los dummys de entrenamiento en Aldrassil se salen de su lugar ,en la zona inicial de los elfos nocturnos
![WoWScrnShot_090622_005945](https://user-images.githubusercontent.com/112668899/188544195-5ba0b096-abec-43e9-bec4-16e8b49c8d97.jpg)
![WoWScrnShot_090622_005953](https://user-images.githubusercontent.com/112668899/188544209-4a989bce-f8a1-40dd-9cd1-a3d496e7a2a5.jpg)

### Comportamiento esperado Blizzlike

no deben moverse de su zona al golpearlos

### Enlaces

https://es.wowhead.com/npc=44614/mu%C3%B1eco-de-entrenamiento#screenshots

### Pasos para reproducir el problema

1. 
2. 
3. 
4.

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/6c8b4fd4203d099c0020cf24f6c30c9ff75e6c59

### Sistema operativo

Debian 11

### Servidor

Firelands

**Comment by pangolp** [comment]
Gracias. Bien, tienen el mismo problema entonces que los otros dummys. Así que los vamos a añadir al arregló que ya tenemos. Luego habrá que probarlos y ver que les entregué la quest a los jugadores cuándo practican por primera vez los spells iniciales. Pero eso va a ser luego, dado que hay que probar varias clases y razas.

**Comment by kuramajssken001** [comment]
Aguarde por favor pela fusão.
