### ISSUE TITLE
[Draeneis][Valle Ammen] Quest 9303 Inoculación

### ISSUE THREAD

**Issue by RaistlinM84** [FirelandsProject/bugtracker#7]
### ¿Con qué cliente juegas?

esES

### Faction

Alianza

### Comportamiento actual

Al Utilizar el [[Cristal Incoulador [Item=22962]](https://es.tbc.wowhead.com/item=22962/cristal-inoculador) sobre [Buhíco cubrebosque inoculado [Npc=16534]](https://es.tbc.wowhead.com/npc=16534/buh%C3%ADco-cubrebosque-inoculado) nos indica que no podemos hacer eso impidiendo completar la misión.

### Comportamiento esperado Blizzlike

Deberia dejar usar el [Cristal Incoulador [Item=22962]](https://es.tbc.wowhead.com/item=22962/cristal-inoculador) sobre [Buhíco cubrebosque inoculado [Npc=16534]](https://es.tbc.wowhead.com/npc=16534/buh%C3%ADco-cubrebosque-inoculado) y asi  poder completar la misión.

### Enlaces

Enlace a la descripción de la misión en Wowhead: [Inoculación](https://es.tbc.wowhead.com/quest=9303/inoculaci%C3%B3n)

Enlace al video de como debería suceder la misión:
https://www.youtube.com/embed/JlfF6FgPPUQ

### Pasos para reproducir el problema

1. Crear un Draenei.
2. Seguir la cadena de misiones que inicia con la misión: [El vindicador Aldar](https://es.tbc.wowhead.com/quest=10304/el-vindicador-aldar)
3. Llegar al punto donde se encuentran los Buhíco cubrebosque
4. Usar el item otorgado por la misión.

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/6c8b4fd4203d099c0020cf24f6c30c9ff75e6c59

### Sistema operativo

Windows 10

### Servidor

Firelands

**Comment by pangolp** [comment]
Buen reporte. Habrá que testearlo. Intentare hacerlo. En caso de que se confirme, habría que ponerlo en ingles de ultima, para subirlo a los issue del repositorio y luego, ver de armar el pull request. Lo bueno de esto, es que podemos debatir en español. En el otro no, tiene que ser todo en ingles, dado que no todos son de habla hispana.

**Comment by kuramajssken001** [comment]
No se encontraron problemas. Lo he probado muchas veces.

**Comment by RaistlinM84** [comment]
@kuramajssken001 en mi emulador si daba error la misión al usar el ítem de la misión tanto con el mob targeteado como no me salía el mensaje de que no podía usarlo en ese momento

**Comment by pangolp** [comment]
> @kuramajssken001 en mi emulador si daba error la misión al usar el ítem de la misión tanto con el mob targeteado como no me salía el mensaje de que no podía usarlo en ese momento.
> 
> En realidad son misiones que ya e visto erróneas en otro proyecto.

**kuramajssken** no habla español. Habla Chino en realidad, yo voy a tratar de hablar con el y explicarle, porque me parece que no sabe o no comprendió muy bien el uso de este bugtracker. Tratare de explicarle luego, no te preocupes, pero seguramente se equivoco, o malinterpreto algo, ya sea en el reporte, o en el uso de este espacio.

**Comment by RaistlinM84** [comment]
a vale no pasa nada es que me resulto raro porque tengo el core compilado de el mismo dia que testee la mision  ^^

**Comment by pangolp** [comment]
Esto en la 3.3.5a, creo que tampoco funcionaba, yo había eliminado en un momento el tema del cambio del template, y luego tuvimos un debate, donde me di cuenta que había un cambio en el nombre del npc, que no me había dado cuenta. ¿Cambia a amistoso acá el npc? Porque si es asi, según los videos, estaría mal y estaría teniendo el mismo error que en la 3.3.5a.

**Comment by pangolp** [comment]
- https://github.com/chromiecraft/chromiecraft/issues/3775
- https://github.com/azerothcore/azerothcore-wotlk/issues/12391
- https://github.com/azerothcore/azerothcore-wotlk/pull/12393
